### ISSUE TITLE
Add Libraries to Phant.io

### ISSUE THREAD

**Issue by toddtreece** [sparkfun/phant-docs#1]
Phant libraries are starting to pop up in comments on sites like hacker news: https://news.ycombinator.com/item?id=8015354

I'm going to use this issue to collect the links as I see them.

**Comment by toddtreece** [comment]
Python: https://github.com/matze/python-phant

**Comment by toddtreece** [comment]
Python: https://bitbucket.org/boomlinde/pyphant

**Comment by girishso** [comment]
Ruby:
PhantRb
https://github.com/girishso/phant_rb

**Comment by toddtreece** [comment]
@girishso added.  thanks!

**Comment by romainmp** [comment]
Wrote a library for Spark Core https://github.com/romainmp/phant , inspired by https://github.com/sparkfun/phant-arduino

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
