### ISSUE TITLE
Phant configuration

### ISSUE THREAD

**Issue by MrEarl** [sparkfun/phant-docs#10]
I installed phant on my machine and I was curious about how/where to configure it.
Especially the data limit (at the moment 2048 mb; 50 mb online) and the rate limits (100 requests in 15 minutes online, but couldn't find out about 'offline' limits) are interesting in the first place.
If there are any other configuration possibilities I would be glad to hear about them.
I found out that all the js files are in the npm modules folder and the db is in user home but I could not find any configuration files (at least no files that you would normally use for configs).

Could somebody give me a hint where to look please?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
