### ISSUE TITLE
Production Deployment Documentation

### ISSUE THREAD

**Issue by mtngit14** [sparkfun/phant-docs#11]
We are interested in deploying Phant to a cloud service (AWS, Google, Azure,..) with MQTT messaging and MongoDB backend for persistent data storage to provide a database for graphing IoT time series data. 
Phant is interesting to us because we have decided to standardize on JS and Node from sensor reading to cloud programming.
On July 23, 2014 the post indicates that documentation to support production deployment would soon be released. I have searched Sparkfun's pages including Github and have been unable to find explicit documentation. Am I missing a repository or did this not get published or were existing docs deemed sufficient? 
I would not expect a full set of docs for my specific architecture but having a cohesive guide for the base system would be useful rather than treating elements as separate components. I am concerned with considerations of a production deployment particularly whether there was going to be User Authentication and Authorization and SSL/TLS security handling. 
Should we just pursue using Mosca?

Thanks
David

**Comment by ToniCorinne** [comment]
We are actually in the process of updating and cleaning up phant to make deploys easier. Hopefully @zinefer will be able to give you a timeline of when that will be released.

**Comment by mtngit14** [comment]
Thanks for the update.

David J. Richards
Managing Member
Axeon Investments Ltd.
T. 303.638.0653 MST (GMT-7)
E. djrichards@axeoninvestments.com

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
