### ISSUE TITLE
Hosting our own production of phant - but it does not receive any data we send

### ISSUE THREAD

**Issue by lautiamkok** [sparkfun/phant-docs#12]
Hi,

We are interested in deploying our own production version of phant, We have set up phant on our own server and got it running at port 8080. We have tried to send some data to the server and it doesn't work. The data is being sent however there is no response from the Phant and the server does not receive it.

Is it because we are using xxx.xxx.xxx.xx:8080 for our server address rather than a subdomain such as data.sparkfun.com?

I have also installed phant on my local server and I can access Phant on http://127.0.0.1:8080 just as the version on our production server http://xxx.xxx.xxx.xx:8080/

Any ideas why? Any further information/ documentation what we can do with phant after installation?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
