### ISSUE TITLE
JPhant

### ISSUE THREAD

**Issue by JPhant** [sparkfun/phant-docs#4]
I am working on a Java Library for Phant (JPhant.) Fully configurable so one program can work with several Data Streams. Read/write in raw formats (csv, json, jsonp,) or use it's built-in data structures for getData and addData...

1) String[][] aaExample = { {"Field1", "Field2"}, {"Value1", "Value2"}...}

2) ArrayList&lt;ArrayList&lt;String&gt;&gt;

with conversions that to/from those two data structures.

I will upload when it's developed further...

**Comment by toddtreece** [comment]
added
